[project]
name = "s3-event-deduplicator"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "aws-lambda-powertools[aws-sdk]>=3.22.1",
    "boto3>=1.40.72",
    "fastjsonschema>=2.21.2",
    "mypy-boto3-dynamodb>=1.40.56",
    "mypy-boto3-sns>=1.40.57",
    "pydantic>=2.12.4",
]

[dependency-groups]
dev = [
    "bandit>=1.8.6",
    "coverage>=7.11.3",
    "moto>=5.1.16",
    "pylint>=4.0.2",
    "pytest>=9.0.1",
    "pytest-socket>=0.7.0",
    "validators>=0.35.0",
]
